apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager
spec:
  dnsNames:
    - sal-kubernites.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: sal-selfsigned